[package]
name = "wealth-manager"
version = "0.1.0"
edition = "2021"
authors = ["cellan"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.162"
serde_json = "1.0.96"
chrono = "0.4.24"
rand = "0.8.5"